language: java
jdk:
  - oraclejdk8
sudo: required
cache:
  directories:
    - $HOME/.m2
script:
    - mvn package
    - curl http://www.jpm4j.org/install/script > jpmInstall.sh
    - sudo sh jpmInstall.sh
    - sudo jpm install com.codacy:codacy-coverage-reporter:assembly
    - codacy-coverage-reporter -l Java -r target/site/jacoco/jacoco.xml
addons:
  artifacts:
    paths:
    - $(git ls-files -o | grep -v lib | grep -v wrapper | grep -e jar$ -e war$ | tr "\n" ":")