language: java
jdk:
  - oraclejdk8
sudo: required
cache:
  directories:
    - $HOME/.m2
script:
    - mvn package
    - curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar >t.jar
    - java -jar t.jar init
    - sudo jpm install com.codacy:codacy-coverage-reporter:assembly
    - codacy-coverage-reporter -l Java -r target/site/jacoco/jacoco.xml
addons:
  artifacts:
    paths:
    - $(git ls-files -o | grep -v lib | grep -v wrapper | grep -e jar$ -e war$ | tr "\n" ":")