language: java
jdk:
  - oraclejdk8
sudo: required
cache:
  directories:
    - $HOME/.m2
script:
    - mvn package -Dlive=true
    - mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken=$CODACY_PROJECT_TOKEN -DapiToken=$CODACY_PROJECT_TOKEN
addons:
  artifacts:
    paths:
    - $(git ls-files -o | grep -v lib | grep -v wrapper | grep -e jar$ -e war$ | tr "\n" ":")