language: java
sudo: required
addons:
  chrome: stable
  apt:
    packages:
    - jq
    - wget
    - curl
    - libssl1.0.0
    - sshpass
  artifacts:
    paths:
    - $(git ls-files -o | grep -v lib | grep -v wrapper | grep -e jar$ -e war$ | tr "\n" ":")
services:
- docker
cache:
  directories:
  - $HOME/.m2
before_install:
- wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- mvn package -Dlive=true
after_success:
- java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r bitcoin/project-back-end/target/site/jacoco/jacoco.xml
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push $DOCKER_USERNAME/blockchain2graph-bitcoin
- docker push $DOCKER_USERNAME/blockchain2graph-bitcoin-benchmark
- sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no ci@5.196.65.205 'docker pull straumat/blockchain2graph-bitcoin-benchmark:2.3-SNAPSHOT'
- sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no ci@5.196.65.205 'nohup docker run -e SPRING_MAIL_PASSWORD=$SPRING_MAIL_PASSWORD -e SPRING_DATA_NEO4J_URI=file:///graph.db -e BUILD_NUMBER=$TRAVIS_BUILD_NUMBER straumat/blockchain2graph-bitcoin-benchmark:2.3-SNAPSHOT > /home/ci/logs-ci &'