language: java
sudo: required
addons:
  chrome: stable
services:
  - docker
cache:
  directories:
    - $HOME/.m2
before_install:
    - sudo apt-get install jq wget curl libssl1.0.0
    - curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest
    - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
script:
    - mvn package -P war -Dlive=true
after_success:
    - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r project-back-end/target/site/jacoco/jacoco.xml
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push $DOCKER_USERNAME/blockchain2graph
addons:
  artifacts:
    paths:
    - $(git ls-files -o | grep -v lib | grep -v wrapper | grep -e jar$ -e war$ | tr "\n" ":")
