version: '2'
services:
  bitcoin:
    image: kylemanna/bitcoind
    ports:
      - 8332:8332
    environment:
      - TXINDEX=1
      - RPCUSER=bitcoinrpc
      - RPCPASSWORD=JRkDy3tgCYdmCEqY1VdfdfhTswiRva
      - REST=1
  neo4j:
    image: neo4j:3.1.4
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/neo4j123
  tomcat:
    image: tomcat
    ports:
      - 8080:8080
    volumes:
      - ./target/blockchain2graph.war:/usr/local/tomcat/webapps/blockchain2graph.war
    links:
      - bitcoin
      - neo4j
    environment:
      - BLOCKCHAIN2GRAPH_ADDRESS=localhost
      - BITCOIND_HOSTNAME=bitcoin
      - BITCOIND_USERNAME=bitcoinrpc
      - BITCOIND_PASSWORD=JRkDy3tgCYdmCEqY1VdfdfhTswiRva
      - SPRING_DATA_NEO4J_URI=bolt://neo4j:neo4j123@neo4j:7687